
site_name: Contenidos UDP
site_description: Repositorio de apuntes y ayudantías
site_url: https://<Lucho-Pizarro>.github.io/udp-cursos
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight
    - search.suggest
  language: es
  palette:
    - scheme: default
      primary: red
      accent: grey
    - scheme: slate
      primary: red
      accent: white
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
  logo: images/udp_logo.png
  favicon: images/udp_logo.png
nav:
  - Inicio: index.md
  - Ramos:
    - Econometría: ramos/econometria.md
    - Microeconomía: ramos/microeconomia.md
    - Macroeconomía: ramos/macroeconomia.md
  - Sobre mí: about.md
plugins:
  - search
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tasklist
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lucho-Pizarro/Udp-Cursos
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/ignacio-pizarro17
    - icon: fontawesome/brands/whatsapp
      link: https://chat.whatsapp.com/HsRUIc4nSjg3zlM19VKPLe?mode=ems_copy_t
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alvarogatica/ 
