
site_name: Contenidos UDP
site_description: Repositorio de apuntes y ayudantías
site_url: https://<Lucho-Pizarro>.github.io/udp-cursos
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight
    - search.suggest
  language: es
  palette:
    - scheme: default
      primary: red
      accent: grey
    - scheme: slate
      primary: red
      accent: white
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
  logo: images/udp_logo.png
  favicon: images/udp_logo.png
nav:
  - Inicio: index.md
  - Ramos:
    - Econometría: ramos/econometria.md
    - Microeconomía: ramos/microeconomia.md
    - Macroeconomía: ramos/macroeconomia.md
  - Tutorías:
      - Programación:
          - General: tutorias/programacion/index.md
          - Tutores:
              - Tutor 1: tutorias/programacion/tutores/tutor1.md
              - Tutor 2: tutorias/programacion/tutores/tutor2.md
              - Tutor 3: tutorias/programacion/tutores/tutor3.md
              - Tutor 4: tutorias/programacion/tutores/tutor4.md
              - Tutor 5: tutorias/programacion/tutores/tutor5.md
      - Matemáticas I:
          - General: tutorias/matematicas-1/index.md
          - Tutores:
              - Tutor 1: tutorias/matematicas-1/tutores/tutor1.md
              - Tutor 2: tutorias/matematicas-1/tutores/tutor2.md
              - Tutor 3: tutorias/matematicas-1/tutores/tutor3.md
              - Tutor 4: tutorias/matematicas-1/tutores/tutor4.md
              - Tutor 5: tutorias/matematicas-1/tutores/tutor5.md
      - Matemáticas II:
          - General: tutorias/matematicas-2/index.md
          - Tutores:
              - Tutor 1: tutorias/matematicas-2/tutores/tutor1.md
              - Tutor 2: tutorias/matematicas-2/tutores/tutor2.md
              - Tutor 3: tutorias/matematicas-2/tutores/tutor3.md
              - Tutor 4: tutorias/matematicas-2/tutores/tutor4.md
              - Tutor 5: tutorias/matematicas-2/tutores/tutor5.md
      - Matemáticas III:
          - General: tutorias/matematicas-3/index.md
          - Tutores:
              - Tutor 1: tutorias/matematicas-3/tutores/tutor1.md
              - Tutor 2: tutorias/matematicas-3/tutores/tutor2.md
              - Tutor 3: tutorias/matematicas-3/tutores/tutor3.md
              - Tutor 4: tutorias/matematicas-3/tutores/tutor4.md
              - Tutor 5: tutorias/matematicas-3/tutores/tutor5.md
      - Contabilidad I:
          - General: tutorias/contabilidad-1/index.md
          - Tutores:
              - Tutor 1: tutorias/contabilidad-1/tutores/tutor1.md
              - Tutor 2: tutorias/contabilidad-1/tutores/tutor2.md
              - Tutor 3: tutorias/contabilidad-1/tutores/tutor3.md
              - Tutor 4: tutorias/contabilidad-1/tutores/tutor4.md
              - Tutor 5: tutorias/contabilidad-1/tutores/tutor5.md
      - Contabilidad II:
          - General: tutorias/contabilidad-2/index.md
          - Tutores:
              - Tutor 1: tutorias/contabilidad-2/tutores/tutor1.md
              - Tutor 2: tutorias/contabilidad-2/tutores/tutor2.md
              - Tutor 3: tutorias/contabilidad-2/tutores/tutor3.md
              - Tutor 4: tutorias/contabilidad-2/tutores/tutor4.md
              - Tutor 5: tutorias/contabilidad-2/tutores/tutor5.md
      - Econometría I:
          - General: tutorias/econometria-1/index.md
          - Tutores:
              - Tutor 1: tutorias/econometria-1/tutores/tutor1.md
              - Tutor 2: tutorias/econometria-1/tutores/tutor2.md
              - Tutor 3: tutorias/econometria-1/tutores/tutor3.md
              - Tutor 4: tutorias/econometria-1/tutores/tutor4.md
              - Tutor 5: tutorias/econometria-1/tutores/tutor5.md
      - Estadística I:
          - General: tutorias/estadistica-1/index.md
          - Tutores:
              - Tutor 1: tutorias/estadistica-1/tutores/tutor1.md
              - Tutor 2: tutorias/estadistica-1/tutores/tutor2.md
              - Tutor 3: tutorias/estadistica-1/tutores/tutor3.md
              - Tutor 4: tutorias/estadistica-1/tutores/tutor4.md
              - Tutor 5: tutorias/estadistica-1/tutores/tutor5.md
      - Estadística II:
          - General: tutorias/estadistica-2/index.md
          - Tutores:
              - Tutor 1: tutorias/estadistica-2/tutores/tutor1.md
              - Tutor 2: tutorias/estadistica-2/tutores/tutor2.md
              - Tutor 3: tutorias/estadistica-2/tutores/tutor3.md
              - Tutor 4: tutorias/estadistica-2/tutores/tutor4.md
              - Tutor 5: tutorias/estadistica-2/tutores/tutor5.md
      - Finanzas I:
          - General: tutorias/finanzas-1/index.md
          - Tutores:
              - Álvaro Gatica: tutorias/finanzas-1/tutores/tutor1.md
              - Tutor 2: tutorias/finanzas-1/tutores/tutor2.md
              - Tutor 3: tutorias/finanzas-1/tutores/tutor3.md
              - Tutor 4: tutorias/finanzas-1/tutores/tutor4.md
              - Tutor 5: tutorias/finanzas-1/tutores/tutor5.md
      - Macroeconomía I:
          - General: tutorias/macroeconomia-1/index.md
          - Tutores:
              - Tutor 1: tutorias/macroeconomia-1/tutores/tutor1.md
              - Tutor 2: tutorias/macroeconomia-1/tutores/tutor2.md
              - Tutor 3: tutorias/macroeconomia-1/tutores/tutor3.md
              - Tutor 4: tutorias/macroeconomia-1/tutores/tutor4.md
              - Tutor 5: tutorias/macroeconomia-1/tutores/tutor5.md
      - Macroeconomía II:
          - General: tutorias/macroeconomia-2/index.md
          - Tutores:
              - Tutor 1: tutorias/macroeconomia-2/tutores/tutor1.md
              - Tutor 2: tutorias/macroeconomia-2/tutores/tutor2.md
              - Tutor 3: tutorias/macroeconomia-2/tutores/tutor3.md
              - Tutor 4: tutorias/macroeconomia-2/tutores/tutor4.md
              - Tutor 5: tutorias/macroeconomia-2/tutores/tutor5.md
      - Microeconomía I:
          - General: tutorias/microeconomia-1/index.md
          - Tutores:
              - Tutor 1: tutorias/microeconomia-1/tutores/tutor1.md
              - Tutor 2: tutorias/microeconomia-1/tutores/tutor2.md
              - Tutor 3: tutorias/microeconomia-1/tutores/tutor3.md
              - Tutor 4: tutorias/microeconomia-1/tutores/tutor4.md
              - Tutor 5: tutorias/microeconomia-1/tutores/tutor5.md
      - Microeconomía II:
          - General: tutorias/microeconomia-2/index.md
          - Tutores:
              - Tutor 1: tutorias/microeconomia-2/tutores/tutor1.md
              - Tutor 2: tutorias/microeconomia-2/tutores/tutor2.md
              - Tutor 3: tutorias/microeconomia-2/tutores/tutor3.md
              - Tutor 4: tutorias/microeconomia-2/tutores/tutor4.md
              - Tutor 5: tutorias/microeconomia-2/tutores/tutor5.md
  - Sobre mí: about.md
plugins:
  - search
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tasklist
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lucho-Pizarro/Udp-Cursos
    - icon: fontawesome/brands/whatsapp
      link: https://chat.whatsapp.com/HsRUIc4nSjg3zlM19VKPLe?mode=ems_copy_t
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alvarogatica/ 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ignacio-pizarro17/
